
- hosts: all
  tasks:
    - name: "Task to reproduce ansible_failed_task undefined issue"
      vars:
        numbers: "{{ [0,1,2,3] }}"
      block:
        - name: "Task inside the block"
          debug: 
            msg:"{{ item/0 }}"
          loop: "{{ numbers }}"
      rescue:
        - name: "Rescue block to handle error"
          debug: 
            msg: "Caught the following exception while executing the block: {{ ansible_failed_task }}"
