
---
- name: Test S3 Bucket error with Minio
  hosts: all
  gather_facts: false
  vars:
    s3_bucket_name: "test-bucket"
    s3_end_point: "http://10.1.1.1:9000"
  tasks:
  - name: Test Get Bucket Versioning
    s3_bucket_info:
      aws_access_key: "{{ random_alpha_numeric(10) }}"
      aws_secret_key: "{{ random_alpha_numeric(20) }}"
      s3_bucket: "{{ s3_bucket_name }}"
      s3_endpoint_url: "{{ s3_end_point }}"
      validate_certs: no
      versioning: 'false'
    ignore_errors: true
  - name: Test Bucket Not Found
    s3_bucket_info:
      aws_access_key: "{{ random_alpha_numeric(10) }}"
      aws_secret_key: "{{ random_alpha_numeric(20) }}"
      s3_bucket: "{{ random_alpha_numeric(5) }}"
      s3_endpoint_url: "{{ s3_end_point }}"
      validate_certs: no
    ignore_errors: true
  - name: Test Access Key Not Found
    s3_bucket_info:
      aws_access_key: "{{ random_alpha_numeric(5) }}"
      aws_secret_key: "{{ random_alpha_numeric(20) }}"
      s3_bucket: "{{ s3_bucket_name }}"
      s3_endpoint_url: "{{ s3_end_point }}"
      validate_certs: no
    ignore_errors: true
  - name: Test Secret Key Not Found
    s3_bucket_info:
      aws_access_key: "{{ random_alpha_numeric(10) }}"
      aws_secret_key: "{{ random_alpha_numeric(8) }}"
      s3_bucket: "{{ s3_bucket_name }}"
      s3_endpoint_url: "{{ s3_end_point }}"
      validate_certs: no
    ignore_errors: true
