
- hosts: all
  gather_facts: no

  tasks:
  - name: Task 1
    debug:
      msg: "Executing task 1"
    async: 10
    poll: 0

  - name: Task 2
    debug:
      msg: "Executing task 2"
    async: 10
    poll: 0

  - name: Task 3
    debug:
      msg: "Executing task 3"
    async: 10
    poll: 0

  - name: Task 4
    debug:
      msg: "Executing task 4"
    async: 10
    poll: 0

  - name: Task 5
    debug:
      msg: "Executing task 5"
    async: 10
    poll: 0

  - name: Task 6
    debug:
      msg: "Executing task 6"
    async: 10
    poll: 0

  - name: Task 7
    debug:
      msg: "Executing task 7"
    async: 10
    poll: 0

  - name: Task 8
    debug:
      msg: "Executing task 8"
    async: 10
    poll: 0

  - name: Task 9
    debug:
      msg: "Executing task 9"
    async: 10
    poll: 0

  # The last task which would encounter issues and give rise to errors
  - name: Task 10
    wait_for:
      host: localhost
      port: 5000
      delay: 10
      timeout: 60
    connection: local
    async: 10
    poll: 0

